# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Addition Operation
#' @param as first operand
#' @param as second operand
add <- function(a, b) {
    .Call('_CalculatorRcpp_add', PACKAGE = 'CalculatorRcpp', a, b)
}

