name: R-CMD-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          install.packages(c("remotes"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("covr")

      - name: Test coverage
        run: covr::codecov()
       #   sudo apt-get install libcurl4-openssl-dev libxml2-dev
       #   R -e 'install.packages("devtools")' 
       #   R -e 'library("devtools")' 
       #   R -e 'devtools::test()
