name: R-CMD-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          R -e 'install.packages("devtools")'
          R -e 'devtools:::test()'
      #    remotes::install_deps(dependencies = TRUE)
      #- name: Check
      #  run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
