name: R-CMD-check1
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Primes
      id: cache-primes
      uses: actions/cache@v2
      with:
        path: prime-numbers
        key: ${{ runner.os }}-prime

    - name: Generate Prime Numbers
      if: steps.cache-primes.outputs.cache-hit != 'true'
      run: sudo apt-get install libcurl4-openssl-dev libxml2-dev
