name: R-CMD-check1
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Prime
      id: cache-prime
      uses: actions/cache@v2
      with:
        path: prime-number
        key: ${{ runner.os }}-dependency

    - name: Generate Prime Numbers
      if: steps.cache-prime.outputs.cache-hit != 'true'
      run: |
       sudo apt-get install libcurl4-openssl-dev libxml2-dev
       R -e 'install.packages("remotes")'
       R -e 'remotes::install_deps(dependencies = TRUE)'
       R -e 'remotes::install_cran("covr")'
