name: R-CMD-check2
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master

    - name: Cache Prime2
      id: cache-prime2
      uses: actions/cache@v2
      with:
        path: prime-number2
        key: ${{ runner.os }}-dependency2

    - name: Generate Prime Numbers
      if: steps.cache-prime2.outputs.cache-hit != 'true'
      run: |
       sudo apt-get install libcurl4-openssl-dev libxml2-dev
     
    - name: Query dependencies1
      run: Rscript -e "install.packages('remotes')" -e "saveRDS(remotes::dev_package_deps(dependencies = TRUE), 'depends.Rds')"
      
    - name: Cache R packages1
      uses: actions/cache@v1
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-r-3.6.1-${{ hashFiles('depends.Rds') }}
        restore-keys: ${{ runner.os }}-r-3.6.1-
       
    - name: Test Package
      run: |
          R -e 'covr::codecov()'
