name: R-CMD-check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
        
      - name: Cache Dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
        
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install libcurl4-openssl-dev libxml2-dev
          R -e 'install.packages("remotes")'
          R -e 'remotes::install_deps(dependencies = TRUE)'
          R -e 'remotes::install_cran("covr")'
          
      - name: Test Package
        run: |
          R -e 'covr::codecov()'
