name: R-CMD-check
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master

    - name: Cache Prime1
      id: cache-prime1
      uses: actions/cache@v2
      with:
        path: prime-number1
        key: ${{ runner.os }}-dependency1

    - name: Generate Prime Numbers
      if: steps.cache-prime1.outputs.cache-hit != 'true'
      run: |
       sudo apt-get install libcurl4-openssl-dev libxml2-dev
       R -e 'install.packages("remotes")'
       R -e 'remotes::install_deps(dependencies = TRUE)'
       R -e 'remotes::install_cran("covr")'
       
    - name: Test Package
      run: R -e 'covr::codecov()'
