name: R-CMD-check1
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master

      - name: Cache openssl
        uses: actions/cache@v1
        id: cache-openssl
        with:
          path: "~/openssl"
          key: "openssl"
          
      - name: Install openssl
        env:
          CACHE_HIT: ${{steps.cache-openssl.outputs.cache-hit}}
        run: |
          echo ${{steps.cache-openssl.outputs.cache-hit}}
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/openssl/* /
          else
            sudo apt-get install libcurl4-openssl-dev libxml2-dev
          fi

      - name: Cache proto
        uses: actions/cache@v1
        id: cache-proto
        with:
          path: "~/proto"
          key: "proto"
          
      - name: Install proto
        env:
          CACHE_HIT: ${{steps.cache-proto.outputs.cache-hit}}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --verbose --force --recursive ~/proto/* /
          else
            R -e 'install.packages("remotes")'
          fi
