name: R-CMD-check1
 
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
 
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@master

    - name: Cache Prime2
      id: cache-prime2
      uses: actions/cache@v2
      with:
        path: prime-number2
        key: ${{ runner.os }}-dependency2

    - name: Generate Prime Numbers
      if: steps.cache-prime2.outputs.cache-hit != 'true'
      run: |
       sudo apt-get install libcurl4-openssl-dev libxml2-dev
     
    - name: R Packages1
      id: r-package1
      uses: actions/cache@v2
      with:
        path: ~/.local/share/renv
        key: ${{ runner.os }}-renv1-${{ hashFiles('**/renv.lock') }}

    - name: Generate Prime Numbers
      if: steps.r-package1.outputs.cache-hit != 'true'
      run: |
       R -e 'install.packages("remotes")'
       R -e 'remotes::install_deps(dependencies = TRUE)'
       R -e 'remotes::install_cran("covr")'
       
    - name: Test Package
      run: |
       .libPaths("~/.local/share/renv")
       R -e 'covr::codecov()'
